export const BANK_OPTIONS = [
  { value: "산업은행", label: "산업은행" },
  { value: "기업은행", label: "기업은행" },
  { value: "국민은행", label: "국민은행" },
  { value: "수협은행", label: "수협은행" },
  { value: "농협은행", label: "농협은행" },
  { value: "우리은행", label: "우리은행" },
  { value: "SC제일은행", label: "SC제일은행" },
  { value: "한국씨티은행", label: "한국씨티은행" },
  { value: "대구은행", label: "대구은행" },
  { value: "부산은행", label: "부산은행" },
  { value: "광주은행", label: "광주은행" },
  { value: "제주은행", label: "제주은행" },
  { value: "전북은행", label: "전북은행" },
  { value: "경남은행", label: "경남은행" },
  { value: "새마을금고", label: "새마을금고" },
  { value: "신협", label: "신협" },
  { value: "우체국", label: "우체국" },
  { value: "하나은행", label: "하나은행" },
  { value: "신한은행", label: "신한은행" },
  { value: "케이뱅크", label: "케이뱅크" },
  { value: "카카오뱅크", label: "카카오뱅크" },
  { value: "토스뱅크", label: "토스뱅크" },
  { value: "기타", label: "기타" },
];
